### ISSUE TITLE
Negativ value color

### ISSUE THREAD

**Issue by vsjoberg** [ecodistrict/IDSSDashboard#162]
When using a KPI with negative values that correspond to change. If we choose a 0 as the "as is" scenario always will be it shows that the 0 is yellow - i.e. it is an ok value. But the 0 we think should be red as what actually happens is that the change isn't doing anything at all - a terrible change which should be indicated as red.

**Comment by andreasrudena** [comment]
I'm puzzled how to solve this. Since you have sufficient -40 and excellent -100 the bad is extrapolated to about 50. So 50 would be a really bad (red) value since that is a change in wrong direction. But if you want zero to be red, that should be bad and it would be the opposite to the default setting (allow only positive values). So one solution is to have another setting "Allow only negative values (and zero)", but that will make zero the worst case possible.. Another problem is that zero cannot be visualized now if zero is the worst value possible since there is no bar to be drawn (the value is a low (bad) as possible). This could be fixed of course, I think it is mentioned in another issue from the Valencia case.

**Comment by andreasrudena** [comment]
Allow negative values are added
