### ISSUE TITLE
Adjust Facilitator/Stakeholder functionalities

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#50]
Stakeholders should only be allowed to adjust their "To Be" scores, not their "As Is" or "Alternative" scores. This means that the Facilitator should be able to set "As Is", "Alternative" (and "To Be") scores for all stakeholders.

**Comment by andreasrudena** [comment]
What about when developing alternatives in combination with qualitative KPI's? Isn't the KPI score different for every KPI in relation to the stakeholder opinion, and even the as is?

Example for qualitative KPIs: 

For a use case the stakeholder thinks as an opinion that the "as is"-situation is bad, the stakeholders ambition (to be) is that the situation should be really good. For alternative A "Create a park" the stakeholder set a high score, for alternative B "Create a parking lot" the stakeholder put a lower score.

At all these cases adjusting the scores are necessary? Otherwise it is very easy for me to disable things for the stakeholder.

**Comment by VincentKamphuis** [comment]
Your are right in that setting the "As Is" and "Alternatives" scores for every stakeholder will be necessary, and the stakeholder's opinion/estimation is important for this, but our suggestion is that the Facilitator adds all these scores to the Dashboard, and not the Stakeholder him-/herself.

**Comment by VincentKamphuis** [comment]
KPI scores are based on KPI (scoring) definition and equal for all stakeholders. Stakeholders can only set their ambitions, weights and minimum scores. This makes the issue irrelevant now.
