### ISSUE TITLE
Unregistered modules

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#64]
The module connection seems buggy. Currently, no modules are registered, while some were a few minutes ago. Also, it should be tested whether KPI scores from module calculations are saved within the Dashboard configuration, also when a module is no longer registered.

**Comment by andreasrudena** [comment]
Did some changes in the latest version that might improve this. Messaging are still not working well but this issue is now more related to issue #62 and the corresponding issue in the framework. Closing this and we'll see if it works better now, pages might need to be reloaded / buttons to be re-clicked.
