### ISSUE TITLE
Add stakeholder functionality doesn't work?

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#81]
It seems like I'm unable to add stakeholders.

![image](https://cloud.githubusercontent.com/assets/12395999/8156796/f2ed3c3a-134f-11e5-9361-00b8b35d704b.png)

**Comment by andreasrudena** [comment]
Since the stakeholder account is unique to enable login for stakeholders, the email is also unique. And right now I generate the email from the stakeholder name. This means that name is unique. In this case there is an old stakeholder left/lost in the system with the same name.

This must be improved in several ways:

Use email field as well?
Definitely show error message when the email is occupied.

**Comment by andreasrudena** [comment]
Using email field from version 1.0.2, the notification is at the top of the page if stakeholder couldn't be created because duplicated email, and that is a separate issue now (to move the notification so that it is always visible).
